# Generated by Django 3.0.7 on 2020-07-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='None', upload_to='blog_pics'),
        ),
    ]
